### ISSUE TITLE
Ауты

### ISSUE THREAD

**Issue by DanilZz** [INFOMCPE/wCasinoFrame#1]
Спиздили у игоря плагин и выдают за свой

**Comment by aquaminer** [comment]
У какого Игоря? Мерзякина? Мы у него ничего не брали внимательно посмотри в код

**Comment by WMaster2** [comment]
Впервые о таком слышу , похожи плагин делал Олег, и продавал за 350р.
И то у нас даже казино работает совершенно по разному , позоже только тем что 3 рамки .
